### ISSUE TITLE
Contextmenu in tracker to change settings

### ISSUE THREAD

**Issue by Mawex** [ori-community/rando-ui#124]
Contextmenu to change tracker settings directly

**Comment by MunWolf** [comment]
Maybe want a hotkey as well you can set to disable/enable tracker mouse through, since you can't really open a context menu if it doesn't register the mouse.

**Comment by timoschwarzer** [comment]
Context menu might be complicated as well since I declare the whole window as the window border (to make it draggable). This has the drawback of not having access to the context menu because it's managed by Windows.
