### ISSUE TITLE
Tracker/Stats don't sync on Linux

### ISSUE THREAD

**Issue by aspiwack** [ori-community/rando-ui#157]
(Initially reported [on Discord](https://discord.com/channels/942484331572658196/942484835631521812/1083296822770020372))

It appears that in recent versions of the randomizer, on Linux, the tracker and the statistics screen don't detect that the game is started (they are endlessly in the waiting state).

Tested on version 2.5.1 on Ubuntu 22.10 with Wine 8.2.

The problem persists after deleting the Wine prefix and letting it be rebuilt.

**Comment by aspiwack** [comment]
On Discord, @timoschwarzer , told me

> If you want to tinker around with it, the issue here is that winestreamproxy does not appear to work. Maybe you can get it to work manually and then tell me the steps you did, then I can compare it to the things the launcher does.

I'd be glad to help, though I don't know quite where to start tinkering. Is it [this winestreamproxy](https://github.com/openglfreak/winestreamproxy)? How do you normally invoke it?

**Comment by timoschwarzer** [comment]
This should be fixed since we changed IPC to use zeromq.
