### ISSUE TITLE
Using "Restore last config" doesn't update the displayed state of the custom header properly

### ISSUE THREAD

**Issue by SiriusAshling** [ori-community/rando-ui#162]
https://cdn.discordapp.com/attachments/942484835631521812/1094249902835499038/2023-04-08_15-17-44.mp4

**Comment by Mawex** [comment]
https://github.com/ori-community/rando-ui/blob/32735b09c8af47dd2f461b87cce2ee52f29d9bf9/components/WotwSeedgen/WorldSettings.vue#L156

that handler doesn't trigger when loading last config. Although it does if you load the last config again/twice

**Comment by timoschwarzer** [comment]
Fixed
