### ISSUE TITLE
Bad error message on syntax error in custom header

### ISSUE THREAD

**Issue by SiriusAshling** [ori-community/rando-ui#163]
Steps:

- Seed Generator, Start from scratch
- "Add custom header", enter `thiserrors`
- "Save"

Expected Result:

Seedgen returns this error, it should be displayed:
```
Error generating seed: Error in header Anonymous Header:
Invalid Expression: Unknown ExpressionIdentKind thiserrors
line 1: thiserrors
        ^^^^^^^^^^
```

Actual Result:

"Error: Request failed with Status code 500"

**Comment by timoschwarzer** [comment]
Fixed
