### ISSUE TITLE
“Restore last config” doesn't seem to restore subconfiguration

### ISSUE THREAD

**Issue by aspiwack** [ori-community/rando-ui#164]
On “restore last config”, in the seed generator. Subconfigurations (like “launch on bingo”'s number of line) don't seem to be restored. The little icon showing that such a subconfiguration has been modified doesn't display. Clicking the subconfiguration menu shows the default values.

Initially [reported on Discord](https://discord.com/channels/942484331572658196/942484835631521812/1094677684501614663).

See also the possibly related #162 ([the theory about the relation](https://discord.com/channels/942484331572658196/942484835631521812/1094731831078813797) would be that the subconfiguration is indeed restored, but the default is displayed).

**Comment by timoschwarzer** [comment]
Fixed
